services:
  mysqldb:
    image: mysql:latest
    container_name: mysql_especial
    environment:
      MYSQL_ROOT_PASSWORD: quimica
    volumes:
      - ./db_files:/docker-entrypoint-initdb.d
    networks:
      - devnet      
    ports:
      - "3306:3306"

  mypy:
    build: 
      context: .
      dockerfile: Dockerfile
    #restart: always
    depends_on:
      - mysqldb
    networks:
      - devnet
    ports:
      - "8080:5000"      
    #command: tail -F /dev/null
    command: python3 app.py

volumes:
  db_data:

networks:
  devnet:
    driver: bridge    